# Generated by Django 4.2 on 2024-06-08 12:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="introduction",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)),
                    django.core.validators.MaxValueValidator(datetime.date(2024, 6, 8)),
                ]
            ),
        ),
    ]
